### PR TITLE
7-bag randomizer to resolve issue #21 on no block repetition

### PR DESCRIPTION
**Pull request by andrewrgarcia**
## brief description of changes this pull request introduce
Implemented a [7-bag randomizer](https://tetris.fandom.com/wiki/Random_Generator) so that a piece is not repeated more than 2 times in a row, which replaces the former random selection of tetrominos. Added a `bag` std::vector<int> object from which to draw tetromino pieces and an algorithm which "fills" the bag every time it becomes empty 

## Related issue/s
Resolves issue #21 no block repetition

## List of files altered
`game.cpp`
`game.hpp`
`main.cpp`

### CODE REVIEW

**Comment by andrewrgarcia** [comment]
@Arsenic-ATG let me know if there's anything else needed to close the issue.

**Review by Arsenic-ATG — COMMENTED** [review]
@andrewrgarcia, looks like you worked on previous copy master branch of your fork which caused duplication of commits ( commits on your fork from previous contribution and commits that were merged/rebased on master branch here have different hash ) this is quite common and is causing merge conflicts in this case.

Though this is not something a simple rebase can't fix, assuming the fact you have allowed editing access by maintainer on this PR, I can take care of this unless you want to give it a go on your own.

**Comment by andrewrgarcia** [comment]
> @andrewrgarcia, looks like you worked on previous copy master branch of your fork which caused duplication of commits ( commits on your fork from previous contribution and commits that were merged/rebased on master branch here have different hash ) this is quite common and is causing merge conflicts in this case.
> 
> Though this is not something a simple rebase can't fix, assuming the fact you have allowed editing access by maintainer on this PR, I can take care of this unless you want to give it a go on your own.

I had not noticed that, thanks for bringing it up. I am fixing this right now and will be sending you a new PR very soon

**Comment by andrewrgarcia** [comment]
Fixed the duplication issue.

**Review by Arsenic-ATG — APPROVED** [review]
Thanks for contributing 😃

**Pull request merged**
